logging:
  level:
    ROOT: DEBUG
    com.employs.co: DEBUG

spring:
  devtools:
    restart:
      enabled: true
      additional-exclude: static/**,.h2.server.properties
    livereload:
      enabled: false # we use Webpack dev server + BrowserSync for livereload
  jackson:
    serialization:
      indent-output: true
  h2:
    console:
      # disable spring boot built-in h2-console since we start it manually with correct configuration
      enabled: false
  mail:
    host: localhost
    port: 25
    username:
    password:
  messages:
    cache-duration: PT1S # 1 second, see the ISO 8601 standard
  r2dbc:
    url: r2dbc:h2:mem:///employes;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: employes
    password:
  thymeleaf:
    cache: false
  sleuth:
    sampler:
      probability: 1 # report 100% of traces
  zipkin: # Use the "zipkin" Maven profile to have the Spring Cloud Zipkin dependencies
    base-url: http://localhost:9411
    enabled: false
    locator:
      discovery:
        enabled: true

server:
  port: 8789

# application:

employs:
  get-all-url: "https://run.mocky.io/v3/dd276bdd-7d47-4803-9b61-8f99d9f02baf"
  get-id-url: "https://dummy.restapiexample.com/api/v1/employee"

#  get-all-url: "https://run.mocky.io/v3/dd276bdd-7d47-4803-9b61-8f99d9f02baf"
#  get-id-url: "https://run.mocky.io/v3/27d8b3bd-ed76-4277-9579-4eacd56bbebb"
